CREATE TABLE LOGIN
(
ID INT IDENTITY(1,1) PRIMARY KEY,
LOGIN VARCHAR(30) NOT NULL,
PASSWORD VARCHAR(255) NOT NULL,
CREATION_DATE DATE NOT NULL,
LAST_PASS_CHAGE DATE NOT NULL,
INVALID_LOGIN_ATTEMPT INT NOT NULL,
ACCOUT_BLOCK INT NOT NULL
)

CREATE TABLE Car
(
ID int IDENTITY(1,1) NOT NULL, 
Producent VARCHAR(255) NOT NULL,
Marka VARCHAR(255) NOT NULL
PRIMARY KEY (ID)
)

CREATE TABLE CAR_DATA
(
ID int IDENTITY(1,1) NOT NULL, 
Rocznik VARCHAR(4) NOT NULL,
Nadwozie VARCHAR(255) NOT NULL,
LiczbaDrzwi INT NOT NULL,
MaxPasazerow INT NOT NULL,
Kolor VARCHAR(255) NOT NULL,
DataPrzegladu VARCHAR(255) NOT NULL,
DataUbezpieczenia VARCHAR(255) NOT NULL,
Przebieg INT NOT NULL,
NumerRejestracyjny VARCHAR(15) NOT NULL,
VIN VARCHAR(20) NOT NULL,
ID_CAR INT
PRIMARY KEY(ID)
FOREIGN KEY (ID_CAR) REFERENCES Car(ID)
)

INSERT INTO LOGIN(LOGIN, PASSWORD, CREATION_DATE, LAST_PASS_CHAGE, INVALID_LOGIN_ATTEMPT, ACCOUT_BLOCK) 
VALUES ('Admin','c1c224b03cd9bc7b6a86d77f5dace40191766c485cd55dc48caf9ac873335d6f','2019-12-12','2019-12-12',0,0) 